---
groups:

- name: FrontEnd-ASP.NET Core
  jobs:
  - web-unit-test
  - web-dev-deploy
  - web-integration
  - web-major
  - web-minor

- name: Backend-NodeJS
  jobs:
  - unit-test
  - dev-rc
  - dev-deploy-iaas
  - dev-deploy-paas
  - dev-deploy-k8s
  - staging-deploy-iaas
  - staging-deploy-paas
  - staging-deploy-k8s
  - integration
  - staging-rc
  - stage-e2e
  - shipit
  - api-major
  - api-minor
   

resources:
 - name: api-nodejs
   type: git
   source:
    uri: {{API-NODEJS-URL}}

 - name: web-asp-dotnet
   type: git
   source:
    uri: {{WEB-NODEJS-URL}}

 - name: api-version
   type: semver
   source:
    driver: git
    uri: {{API-NODEJS-URL}}
    branch: version
    file: version
    username: schabiyo
    password: {{GIT-PASSWORD}}
    initial_version: 1.0.0

 - name: web-version
   type: semver
   source:
    driver: git
    uri: {{WEB-ASP-DOTNET-URL}}
    branch: version
    file: version
    username: schabiyo
    password: {{GIT-PASSWORD}}
    initial_version: 1.0.0
 
 - name: api-nodejs-image
   type: docker-image
   source:
     repository: {{ACR-API-REPOSITORY}}
     username: {{ACR-USERNAME}}
     password: {{ACR-PASSWORD}} 

 - name: web-asp-dotnet-image
   type: docker-image
   source:
     repository: syoossdemoacr.azurecr.io:443/ossdemo/web-asp-dotnet
     username: {{ACR-USERNAME}}
     password: {{ACR-PASSWORD}}

 - name: sqlserver
   type: docker-image
   source:
     repository: microsoft/mssql-server-linux
    

jobs:
  - name: unit-test
    serial: true
    public: false
    plan:
      - aggregate:
        - get: api-nodejs
          trigger: true
        - get: api-version
          param: {pre: rc}
          resource: api-version
          trigger: true
      - task: build-and-test
        file: api-nodejs/ci/tasks/build-and-test.yml
        params:

  - name: web-unit-test
    serial: true
    public: false
    plan:
      - aggregate:
        - get: web-asp-dotnet
        - get: web-version
          resource: web-version
          trigger: true
      - task: unit-test
        file: web-asp-dotnet/ci/tasks/build-and-test.yml
        params:

  - name: dev-rc
    serial_groups: [version]
    plan:
#      - aggregate:
      - get: api-nodejs
        passed: [unit-test]
        trigger: true
      - get: api-version
        resource: api-version
        passed: [unit-test]
        trigger: true
      - task: build-artifact
        file: api-nodejs/ci/tasks/build-rc.yml
      - put: api-nodejs-image
        params:
          - build: api-nodejs
          - tag_as_latest: true
#      - put: api-version
#        params: {file: api-version/number}

  - name: dev-deploy-iaas
    serial_groups: [version]
    plan:
      - get: api-nodejs
        passed: [dev-rc]
        trigger: false
      - get: api-version
      - put: api-version
        params: {file: api-version/number}
      - task: deploy-to-dev-iaas
        file: api-nodejs/ci/tasks/deploy-to-dev-iaas.yml
        params:
          - server_admin_username: {{SERVER-ADMIN-USERNAME}}
          - server_prefix: {{SERVER-PREFIX}}
          - acr_username: {{ACR-USERNAME}}
          - acr_password: {{ACR-PASSWORD}}
          - acr_endpoint: {{ACR-ENDPOINT}}
          - server_location: {{SERVER-LOCATION}}
          - server_ssh_private_key: {{SERVER-SSH-PRIVATE-KEY}}
          - server_ssh_public_key: {{SERVER-SSH-PUBLIC-KEY}}


  - name: dev-deploy-paas
    serial_groups: [version]
    plan:
      - aggregate:
         - get: api-nodejs
           passed: [dev-rc]
           trigger: true
         - get: api-version
           resource: api-version
           passed: [dev-rc]
           trigger: true
      - task: deploy-to-dev-paas
        file: api-nodejs/ci/tasks/deploy-to-dev-paas.yml
        params:
          - service_principal_id: {{SERVICE_PRINCIPAL_ID}}
          - service_principal_secret: {{SERVICE_PRINCIPAL_SECRET}}
          - tenant_id: {{TENANT_ID}}
          - subscription_id: {{SUBSCRIPTION_ID}}
          - paas_rg: {{RG_PAAS}}
          - server_prefix: {{SERVER-PREFIX}}
          - acr_username: {{ACR-USERNAME}}
          - acr_password: {{ACR-PASSWORD}}
          - acr_endpoint: {{ACR-ENDPOINT}}

  - name: dev-deploy-k8s
    serial_groups: [version]
    plan:
      - aggregate:
        - get: api-nodejs
          passed: [dev-rc]
          trigger: true
        - get: api-version
          passed: [dev-rc]
          trigger: true
      - task: deploy-to-dev-k8s
        file: api-nodejs/ci/tasks/deploy-to-dev-k8s.yml
        params:
          - service_principal_id: {{SERVICE_PRINCIPAL_ID}}
          - service_principal_secret: {{SERVICE_PRINCIPAL_SECRET}}
          - tenant_id: {{TENANT_ID}}
          - subscription_id: {{SUBSCRIPTION_ID}}
          - acs_rg: {{RG_ACS_K8S}}
          - server_prefix: {{SERVER-PREFIX}}
          - acr_username: {{ACR-USERNAME}}
          - acr_password: {{ACR-PASSWORD}}
          - acr_endpoint: {{ACR-ENDPOINT}}
          - server_ssh_private_key: {{SERVER-SSH-PRIVATE-KEY}}
          - server_ssh_public_key: {{SERVER-SSH-PUBLIC-KEY}}

  - name: web-dev-deploy
    serial_groups: [version]
    plan:
      - get: web-asp-dotnet
        passed: [web-unit-test]
        trigger: true
      - get: web-version
        param: {pre: rc}
      - task: build-artifact
        file: web-asp-dotnet/ci/tasks/build-rc.yml
      - put: web-asp-dotnet-image
        params:
          - build: web-asp-dotnet
          - tag: web-version/number
      - put: web-version
        params: {file: web-version/number}
      - task: deploy-to-dev
        file: web-asp-dotnet/ci/tasks/deploy-to-dev.yml
       
  - name: integration
    serial: true
    plan:
      - aggregate: 
    #  - get: api-nodejs-image
    #    trigger: true
    #    passed: [dev-deploy-paas]
        - get: api-nodejs
          passed: [dev-deploy-paas]
          trigger: true
        - get: api-version
          resource: api-version
          passed: [dev-deploy-paas]
          trigger: true
      - task: integration
        file: api-nodejs/ci/tasks/integration.yml
        params:

  - name: web-integration
    serial: true
    plan:
      - get: web-asp-dotnet-image
        trigger: true
        passed: [web-dev-deploy]
      - get: web-asp-dotnet
        passed: [web-dev-deploy]
      - task: integration
        file: web-asp-dotnet/ci/tasks/integration.yml

       
  - name: staging-rc
    serial_groups: [version]
    plan:
      - aggregate:
        - get: api-nodejs
          passed: [integration]
          trigger: true
        - get: api-version
          resource: api-version
          passed: [integration]
          params: {bump: rc}
          trigger: true
      - put: api-version
        params: {file: api-version/number}
      - put: api-nodejs-image
        params:
          - build: api-nodejs
          - tag: api-version/number
  
  - name: staging-deploy-iaas
    serial_groups: [version]
    plan:
      - get: api-nodejs
        passed: [staging-rc]
        trigger: false
      - get: api-version
      - put: api-version
        params: {file: api-version/number}
      - task: deploy-to-staging-iaas
        file: api-nodejs/ci/tasks/deploy-to-staging-iaas.yml
        params:
          - server_admin_username: {{SERVER-ADMIN-USERNAME}}
          - server_prefix: {{SERVER-PREFIX}}
          - acr_username: {{ACR-USERNAME}}
          - acr_password: {{ACR-PASSWORD}}
          - acr_endpoint: {{ACR-ENDPOINT}}
          - server_location: {{SERVER-LOCATION}}
          - server_ssh_private_key: {{SERVER-SSH-PRIVATE-KEY}}
          - server_ssh_public_key: {{SERVER-SSH-PUBLIC-KEY}}


  - name: staging-deploy-paas
    serial_groups: [version]
    plan:
      - aggregate:
         - get: api-nodejs
           passed: [staging-rc]
           trigger: true
         - get: api-version
           resource: api-version
           passed: [staging-rc]
           trigger: true
      - task: deploy-to-staging-paas
        file: api-nodejs/ci/tasks/deploy-to-staging-paas.yml
        params:
          - service_principal_id: {{SERVICE_PRINCIPAL_ID}}
          - service_principal_secret: {{SERVICE_PRINCIPAL_SECRET}}
          - tenant_id: {{TENANT_ID}}
          - subscription_id: {{SUBSCRIPTION_ID}}
          - paas_rg: {{RG_PAAS}}
          - server_prefix: {{SERVER-PREFIX}}
          - acr_username: {{ACR-USERNAME}}
          - acr_password: {{ACR-PASSWORD}}
          - acr_endpoint: {{ACR-ENDPOINT}}
  
  - name: staging-deploy-k8s
    serial_groups: [version]
    plan:
#      aggregate:
      - get: api-nodejs
        passed: [staging-rc]
        trigger: true
      - get: api-version
        passed: [staging-rc]
        trigger: true
      - put: api-version
        params: {file: api-version/number}
      - task: deploy-to-staging-k8s
        file: api-nodejs/ci/tasks/deploy-to-staging-k8s.yml
        params:
          - service_principal_id: {{SERVICE_PRINCIPAL_ID}}
          - service_principal_secret: {{SERVICE_PRINCIPAL_SECRET}}
          - tenant_id: {{TENANT_ID}}
          - subscription_id: {{SUBSCRIPTION_ID}}
          - acs_rg: {{RG_ACS_K8S}}
          - server_prefix: {{SERVER-PREFIX}}
          - acr_username: {{ACR-USERNAME}}
          - acr_password: {{ACR-PASSWORD}}
          - acr_endpoint: {{ACR-ENDPOINT}}
          - server_ssh_private_key: {{SERVER-SSH-PRIVATE-KEY}}
          - server_ssh_public_key: {{SERVER-SSH-PUBLIC-KEY}}

  - name: stage-e2e
    serial_groups: [version]
    plan:
      - aggregate:
        - get: api-nodejs
          passed: [staging-deploy-paas]
          trigger: true
        - get: api-version
          resource: api-version
          passed: [staging-deploy-paas]
          trigger: true
          params: {bump: rc}
      - get: sqlserver


  - name: shipit
    serial_groups: [version]
    plan:
      - aggregate:
#      - get: api-nodejs-image
#        passed: [stage-e2e]
        - get: api-nodejs
          passed: [stage-e2e]
          trigger: true
        - get: api-version
          resource: api-version
          passed: [stage-e2e]
          params: {bump: final}
      - put: api-nodejs-image
        params: 
          - build: api-nodejs
          - tag: api-version/number
      - put: api-version
        params: {file: api-version/number}


#Utilities to bump versions

  - name: api-major
    serial_groups: [version]
    plan:
    - put: api-version
      params: {bump: major, pre: rc}

  - name: api-minor
    serial_groups: [version]
    plan:
    - put: api-version
      params: {bump: minor, pre: rc} 


  - name: web-major
    serial_groups: [version]
    plan:
    - put: web-version
      params: {bump: major, pre: rc}

  - name: web-minor
    serial_groups: [version]
    plan:
    - put: web-version
      params: {bump: minor, pre: rc}
