---
groups:

- name: FrontEnd
  jobs:
  - web-unit-test
  - web-dev-rc
  - web-dev-deploy-iaas
  - web-dev-deploy-paas
  - web-dev-deploy-k8s
  - web-integration
  - web-shipit
  - web-major
  - web-minor
#  - web-patch
  - web-production-deploy
  - web-paas-deploy
  - web-k8s-deploy
  - web-iaas-deploy

- name: Backend
  jobs:
  - api-unit-test
  - api-dev-rc
  - api-dev-deploy-iaas
  - api-dev-deploy-paas
  - api-dev-deploy-k8s
  - api-integration
  - api-shipit
  - api-major
  - api-minor
  - api-patch
  - api-production-deploy
   

resources:
 - name: api-nodejs
   type: git
   source:
    uri: {{API-NODEJS-URL}}

 - name: web-nodejs
   type: git
   source:
    uri: {{WEB-NODEJS-URL}}

 - name: api-version
   type: semver
   source:
    driver: git
    uri: {{API-NODEJS-URL}}
    branch: version
    file: version
    username: schabiyo
    password: {{GIT-PASSWORD}}
    initial_version: 1.0.0

 - name: web-version
   type: semver
   source:
    driver: git
    uri: {{WEB-NODEJS-URL}}
    branch: version
    file: version
    username: schabiyo
    password: {{GIT-PASSWORD}}
    initial_version: 1.0.0
 
 - name: api-nodejs-image
   type: docker-image
   source:
     repository: {{ACR-API-REPOSITORY}}
     username: {{ACR-USERNAME}}
     password: {{ACR-PASSWORD}} 

 - name: web-nodejs-image
   type: docker-image
   source:
     repository: syoossdemoacr.azurecr.io:443/ossdemo/web-nodejs
     username: {{ACR-USERNAME}}
     password: {{ACR-PASSWORD}}


jobs:
  - name: api-unit-test
    serial: true
    public: false
    plan:
      - aggregate:
        - get: api-nodejs
          trigger: true
        - get: api-version
          param: {pre: rc}
          resource: api-version
          trigger: true
      - task: build-and-test
        file: api-nodejs/ci/tasks/build-and-test.yml
        params:

  - name: web-unit-test
    serial: true
    public: false
    plan:
      - aggregate:
        - get: web-nodejs
          trigger: true
        - get: web-version
          resource: web-version
 #         trigger: true
      - task: unit-test
        file: web-nodejs/ci/tasks/build-and-test.yml
        params:

  - name: api-dev-rc
    serial_groups: [version]
    plan:
#      - aggregate:
      - get: api-nodejs
        passed: [api-unit-test]
        trigger: true
      - get: api-version
        resource: api-version
        passed: [api-unit-test]
        params: {pre: rc}
        trigger: true
      - task: build-artifact
        file: api-nodejs/ci/tasks/build-rc.yml
      - put: api-nodejs-image
        params:
          - build: api-nodejs
          - tag: api-version/number
      - put: api-version
        params: {file: api-version/number}

  - name: web-dev-rc
    serial_groups: [web-version]
    plan:
      - get: web-nodejs
        passed: [web-unit-test]
        trigger: true
      - get: web-version
        resource: web-version
        passed: [web-unit-test]
        params: {pre: rc} 
        trigger: true
      - task: build-artifact
        file: web-nodejs/ci/tasks/build-rc.yml
      - put: web-nodejs-image
        params:
          - build: web-nodejs
          - tag: web-version/number
      - put: web-version
        params: {file: web-version/number}

  - name: api-dev-deploy-iaas
    serial_groups: [version]
    plan:
      - get: api-nodejs
        passed: [api-dev-rc]
        trigger: false
      - get: api-version
      - put: api-version
        params: {file: api-version/number}
      - task: deploy-to-dev-iaas
        file: api-nodejs/ci/tasks/deploy-to-dev-iaas.yml
        params:
          - server_admin_username: {{SERVER-ADMIN-USERNAME}}
          - server_prefix: {{SERVER-PREFIX}}
          - acr_username: {{ACR-USERNAME}}
          - acr_password: {{ACR-PASSWORD}}
          - acr_endpoint: {{ACR-ENDPOINT}}
          - server_location: {{SERVER-LOCATION}}
          - server_ssh_private_key: {{SERVER-SSH-PRIVATE-KEY}}
          - server_ssh_public_key: {{SERVER-SSH-PUBLIC-KEY}}
 
  - name: web-dev-deploy-iaas
    serial_groups: [web-version]
    plan:
      - get: web-nodejs
        passed: [web-dev-rc]
        trigger: false
      - get: web-version
      - put: web-version
        params: {file: web-version/number}
      - task: deploy-to-dev-iaas
        file: web-nodejs/ci/tasks/deploy-to-dev-iaas.yml
        params:
          - server_admin_username: {{SERVER-ADMIN-USERNAME}}
          - server_prefix: {{SERVER-PREFIX}}
          - acr_username: {{ACR-USERNAME}}
          - location: {{LOCATION}}
          - acr_password: {{ACR-PASSWORD}}
          - acr_endpoint: {{ACR-ENDPOINT}}
          - server_location: {{SERVER-LOCATION}}
          - server_ssh_private_key: {{SERVER-SSH-PRIVATE-KEY}}
          - server_ssh_public_key: {{SERVER-SSH-PUBLIC-KEY}}


  - name: api-dev-deploy-paas
    serial_groups: [version]
    plan:
      - aggregate:
         - get: api-nodejs
           passed: [api-dev-rc]
           trigger: true
         - get: api-version
           resource: api-version
           passed: [api-dev-rc]
           trigger: true
      - task: deploy-to-dev-paas
        file: api-nodejs/ci/tasks/deploy-to-dev-paas.yml
        params:
          - service_principal_id: {{SERVICE_PRINCIPAL_ID}}
          - service_principal_secret: {{SERVICE_PRINCIPAL_SECRET}}
          - tenant_id: {{TENANT_ID}}
          - subscription_id: {{SUBSCRIPTION_ID}}
          - paas_rg: {{RG_PAAS}}
          - server_prefix: {{SERVER-PREFIX}}
          - acr_username: {{ACR-USERNAME}}
          - acr_password: {{ACR-PASSWORD}}
          - acr_endpoint: {{ACR-ENDPOINT}}

  - name: web-dev-deploy-paas
    serial_groups: [web-version]
    plan:
      - aggregate:
#         - get: api-nodejs-image
#           trigger: true
#           passed: [web-dev-deploy-paas]
         - get: web-nodejs
           passed: [web-dev-rc]
           trigger: true
         - get: web-version
           resource: web-version
           passed: [web-dev-rc]
           trigger: true
      - task: deploy-to-dev-paas
        file: web-nodejs/ci/tasks/deploy-to-dev-paas.yml
        params:
          - service_principal_id: {{SERVICE_PRINCIPAL_ID}}
          - service_principal_secret: {{SERVICE_PRINCIPAL_SECRET}}
          - tenant_id: {{TENANT_ID}}
          - subscription_id: {{SUBSCRIPTION_ID}}
          - paas_rg: {{RG_PAAS}}
          - server_prefix: {{SERVER-PREFIX}}
          - acr_username: {{ACR-USERNAME}}
          - acr_password: {{ACR-PASSWORD}}
          - acr_endpoint: {{ACR-ENDPOINT}}


  - name: api-dev-deploy-k8s
    serial_groups: [version]
    plan:
      - aggregate:
        - get: api-nodejs
          passed: [api-dev-rc]
          trigger: true
        - get: api-version
          passed: [api-dev-rc]
          trigger: true
      - task: deploy-to-dev-k8s
        file: api-nodejs/ci/tasks/deploy-to-dev-k8s.yml
        params:
          - service_principal_id: {{SERVICE_PRINCIPAL_ID}}
          - service_principal_secret: {{SERVICE_PRINCIPAL_SECRET}}
          - tenant_id: {{TENANT_ID}}
          - subscription_id: {{SUBSCRIPTION_ID}}
          - acs_rg: {{RG_ACS_K8S}}
          - server_prefix: {{SERVER-PREFIX}}
          - acr_username: {{ACR-USERNAME}}
          - acr_password: {{ACR-PASSWORD}}
          - acr_endpoint: {{ACR-ENDPOINT}}
          - server_ssh_private_key: {{SERVER-SSH-PRIVATE-KEY}}
          - server_ssh_public_key: {{SERVER-SSH-PUBLIC-KEY}}


  - name: web-dev-deploy-k8s
    serial_groups: [web-version]
    plan:
      - aggregate:
        - get: web-nodejs
          passed: [web-dev-rc]
          trigger: true
        - get: web-version
          passed: [web-dev-rc]
          trigger: true
      - task: deploy-to-dev-k8s
        file: web-nodejs/ci/tasks/deploy-to-dev-k8s.yml
        params:
          - service_principal_id: {{SERVICE_PRINCIPAL_ID}}
          - service_principal_secret: {{SERVICE_PRINCIPAL_SECRET}}
          - tenant_id: {{TENANT_ID}}
          - subscription_id: {{SUBSCRIPTION_ID}}
          - acs_rg: {{RG_ACS_K8S}}
          - server_prefix: {{SERVER-PREFIX}}
          - acr_username: {{ACR-USERNAME}}
          - acr_password: {{ACR-PASSWORD}}
          - acr_endpoint: {{ACR-ENDPOINT}}
          - server_ssh_private_key: {{SERVER-SSH-PRIVATE-KEY}}
          - server_ssh_public_key: {{SERVER-SSH-PUBLIC-KEY}}

  - name: api-integration
    serial: true
    plan:
      - aggregate: 
    #  - get: api-nodejs-image
    #    trigger: true
    #    passed: [dev-deploy-paas]
        - get: api-nodejs
          passed: [api-dev-deploy-paas]
          trigger: true
        - get: api-version
          resource: api-version
          passed: [api-dev-deploy-paas]
          trigger: true
      - task: integration
        file: api-nodejs/ci/tasks/integration.yml
        params:

  - name: web-integration
    serial: true
    plan:
#      - get: api-nodejs-image
#        trigger: true
#        passed: [web-dev-deploy-paas]
      - get: web-wersion
        resource: web-version
        trigger: true
        passed: [web-dev-deploy-paas]
      - get: web-nodejs
        passed: [web-dev-deploy-paas]
        trigger: true
      - task: integration
        file: web-nodejs/ci/tasks/integration.yml

       

  - name: api-shipit
    serial_groups: [version]
    plan:
      - aggregate:
#      - get: api-nodejs-image
#        passed: [stage-e2e]
        - get: api-nodejs
          passed: [api-integration]
          trigger: true
        - get: api-version
          resource: api-version
          passed: [api-integration]
          params: {bump: final}
      - put: api-nodejs-image
        params: 
          - build: api-nodejs
          - tag: api-version/number
      - put: api-version
        params: {file: api-version/number}

  - name: web-shipit
    serial_groups: [web-version]
    plan:
      - aggregate:
#        - get: api-nodejs-image
#          passed: [web-integration]
        - get: web-nodejs
          passed: [web-integration]
          trigger: true
        - get: web-version
          resource: web-version
          passed: [web-integration]
          params: {bump: final}
      - put: web-nodejs-image
        params:
          - build: web-nodejs
          - tag: web-version/number
      - put: web-version
        params: {file: web-version/number}

#Utilities to bump versions

  - name: api-major
    serial_groups: [version]
    plan:
    - put: api-version
      params: {bump: major, pre: rc}

  - name: api-minor
    serial_groups: [version]
    plan:
    - put: api-version
      params: {bump: minor, pre: rc} 


  - name: web-major
    serial_groups: [version]
    plan:
    - put: web-version
      params: {bump: major, pre: rc}

  - name: web-minor
    serial_groups: [version]
    plan:
    - put: web-version
      params: {bump: minor, pre: rc}

  - name: api-production-deploy
    serial_groups: [version]
    plan:
    - get: api-version
      params: {bump: final}
    - get: api-nodejs
      passed: [api-shipit]
    - task: deploy-to-production
      file: api-nodejs/ci/tasks/deploy-to-prod-k8s.yml
      params:
        - service_principal_id: {{SERVICE_PRINCIPAL_ID}}
        - service_principal_secret: {{SERVICE_PRINCIPAL_SECRET}}
        - tenant_id: {{TENANT_ID}}
        - subscription_id: {{SUBSCRIPTION_ID}}
        - acs_rg: {{RG_ACS_K8S}}
        - server_prefix: {{SERVER-PREFIX}}
        - acr_username: {{ACR-USERNAME}}
        - acr_password: {{ACR-PASSWORD}}
        - acr_endpoint: {{ACR-ENDPOINT}}
        - server_ssh_private_key: {{SERVER-SSH-PRIVATE-KEY}}
        - server_ssh_public_key: {{SERVER-SSH-PUBLIC-KEY}}

  - name: web-production-deploy
    serial_groups: [web-version]
    plan:
    - get: web-version
      params: {bump: final}
    - get: web-nodejs
      passed: [web-shipit]
  
  - name: web-paas-deploy
    serial_groups: [web-version]
    plan:
    - aggregate:
      - get: web-version
        params: {bump: final}
        passed: [web-production-deploy]
      - get: web-nodejs
        passed: [web-production-deploy]
        trigger: true
    - task: deploy-to-production
      file: web-nodejs/ci/tasks/deploy-to-prod-paas.yml
      params:
        - service_principal_id: {{SERVICE_PRINCIPAL_ID}}
        - service_principal_secret: {{SERVICE_PRINCIPAL_SECRET}}
        - tenant_id: {{TENANT_ID}}
        - subscription_id: {{SUBSCRIPTION_ID}}
        - server_prefix: {{SERVER-PREFIX}}
        - server_ssh_private_key: {{SERVER-SSH-PRIVATE-KEY}}
        - server_ssh_public_key: {{SERVER-SSH-PUBLIC-KEY}}
 
  - name: web-iaas-deploy
    serial_groups: [web-version]
    plan:
    - aggregate:
      - get: web-version
        params: {bump: final}
        passed: [web-production-deploy]
      - get: web-nodejs
        passed: [web-production-deploy]
        trigger: true
    - task: deploy-to-production
      file: web-nodejs/ci/tasks/deploy-to-prod-iaas.yml
      params:
        - service_principal_id: {{SERVICE_PRINCIPAL_ID}}
        - service_principal_secret: {{SERVICE_PRINCIPAL_SECRET}}
        - tenant_id: {{TENANT_ID}}
        - subscription_id: {{SUBSCRIPTION_ID}}
        - server_prefix: {{SERVER-PREFIX}}
        - server_ssh_private_key: {{SERVER-SSH-PRIVATE-KEY}}
        - server_ssh_public_key: {{SERVER-SSH-PUBLIC-KEY}}

  - name: web-k8s-deploy
    serial_groups: [web-version]
    plan:
    - aggregate:
      - get: web-version
        params: {bump: final}
        passed: [web-production-deploy]
      - get: web-nodejs
        passed: [web-production-deploy]
        trigger: true
    - task: deploy-to-production
      file: web-nodejs/ci/tasks/deploy-to-prod-k8s.yml
      params:
        - service_principal_id: {{SERVICE_PRINCIPAL_ID}}
        - service_principal_secret: {{SERVICE_PRINCIPAL_SECRET}}
        - tenant_id: {{TENANT_ID}}
        - subscription_id: {{SUBSCRIPTION_ID}}
        - acs_rg: {{RG_ACS_K8S}}
        - server_prefix: {{SERVER-PREFIX}}
        - acr_username: {{ACR-USERNAME}}
        - acr_password: {{ACR-PASSWORD}}
        - acr_endpoint: {{ACR-ENDPOINT}}
        - server_ssh_private_key: {{SERVER-SSH-PRIVATE-KEY}}
        - server_ssh_public_key: {{SERVER-SSH-PUBLIC-KEY}}
# - name: web-patch
#    serial_groups: [web-version]
#    plan:
#    - get: web-version
#      passed: [web-shipit]
#      trigger: true
#    - put: web-version
#      params: {bump: patch, pre: rc}

  - name: api-patch
    serial_groups: [version]
    plan:
    - get: api-version
      passed: [api-shipit]
      trigger: true
    - put: api-version
      params: {bump: patch, pre: rc}
