---
# This playbook installs and configures all the items necessary for building out the demo's'
- name: Install tools
  hosts: buildbox
  remote_user: VALUEOF_DEMO_ADMIN_USER
  sudo : true 

  tasks: 
  - name: update YUM
    yum: name=* state=latest
  
  - name: Install epel
    yum: name=epel-release state=latest

  - name: Install python and pip
    yum: name=python-pip state=latest
  
  - name: install Git
    yum: name=git state=latest

  - name: install Ansible
    yum: name=ansible state=latest

# Install the latest version of the Azure CLI - https://docs.microsoft.com/en-us/cli/azure/install-azure-cli
# This doesnt work as the install script currently asks for paramters
  - name: install pre-req for CLI
    command: yum install -y gcc libffi-devel python-devel openssl-devel
  #- name: Install the CLI of azure
  #  command: curl -L https://aka.ms/InstallAzureCli | bash
  #  args:
  #    chdir: /source

# Install additional tools
  - name: install autoconf
    yum: name=autoconf state=latest
  - name: install automake
    yum: name=automake state=latest
  
