---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: schabiyo/ossdemo 
    tag: latest

params:
  service_principal_id: 
  service_principal_secret:
  tenant_id:
  subscription_id:
  oms_workspace_name:
  utility_rg:


inputs:
  - name: azure-oss-demos-ci

run:
  path: azure-oss-demos-ci/oms/tasks/delete-oms-workspace.sh
