---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: schabiyo/ossdemo 
    tag: latest

params:
  service_principal_id: 
  service_principal_secret:
  tenant_id:
  subscription_id:
  location:
  registry_name:
  server_admin_username:
  registry_admin_username:
  registry_admin_password:
  server_prefix:
  server_ssh_private_key:
  server_ssh_public_key:
  demo_admin_email:


inputs:
  - name: azure-ossdemos-git

run:
  path: azure-ossdemos-git/infra-provisioning/paas/tasks/create-webplan.sh
