---
groups:
- name: Deploy Jumpbox
  jobs:
  - validate-input
  - create-jumpbox
  - validate-jumpbox
   
- name: Destroy Jumpbox
  jobs:
  - destroy-jumpbox


resources:
- name: azure-oss-demos-ci
  type: git
  source:
    uri: https://github.com/schabiyo/azure-oss-demos.git
    branch: master

- name: azure-oss-demos
  type: git
  source:
    uri: https://github.com/dansand71/OSSonAzure.git
    branch: master

jobs:
- name: validate-input
  plan:
  - get: azure-oss-demos-ci
  - task: validate-input
    file: azure-oss-demos-ci/jumpbox/tasks/validate-input.yml
    params:
      service_principal_id: {{SERVICE_PRINCIPAL_ID}}
      service_principal_secret: {{SERVICE_PRINCIPAL_SECRET}}
      tenant_id: {{TENANT_ID}}
      subscription_id: {{SUBSCRIPTION_ID}}
      storage_account_prefix: {{STORAGE_ACCOUNT_PREFIX}} 

- name: create-jumpbox
  plan:
  - get: azure-oss-demos-ci
    passed: [validate-input]
    triggered: true
  - get: azure-oss-demos
  - task: build-jumpbox
    file: azure-oss-demos-ci/jumpbox/tasks/create-jumpbox.yml
    params:
      service_principal_id: {{SERVICE_PRINCIPAL_ID}}
      service_principal_secret: {{SERVICE_PRINCIPAL_SECRET}}
      tenant_id: {{TENANT_ID}}
      subscription_id: {{SUBSCRIPTION_ID}}
      storage_account_prefix: {{STORAGE_ACCOUNT_PREFIX}}
      jumpbox_prefix: {{JUMPBOX_PREFIX}}
      jumpbox_admin: {{JUMPBOX_ADMIN}}
      jumpbox_admin_password: {{JUMPBOX_ADMIN_PASSWORD}}
      jumpbox_ssh_private_key: {{JUMPBOX_SSH_PRIVATE_KEY}}
      jumpbox_ssh_public_key: {{JUMPBOX_SSH_PUBLIC_KEY}}
      utility_rg: {{RG_UTILITY}}
      location: {{LOCATION}}
  - aggregate:
    - task: ansible-configure-dotnet-core
      file: azure-oss-demos-ci/jumpbox/tasks/configure-dotnet-core.yml
    - task: ansible-configure-vs-code
      file: azure-oss-demos-ci/jumpbox/tasks/configure-vs-code.yml
      params:
        jumpbox_prefix: {{JUMPBOX_PREFIX}}
        jumpbox_admin: {{JUMPBOX_ADMIN}}
        jumpbox_admin_password: {{JUMPBOX_ADMIN_PASSWORD}}
        location: {{LOCATION}}

- name: validate-jumpbox 
  plan:
    - get: azure-oss-demos-ci
      passed: [create-jumpbox]
    - task: validate-jumpbox
      file: azure-oss-demos-ci/jumpbox/tasks/validate-jumpbox.yml

- name: destroy-jumpbox
  plan:
  - get: azure-oss-demos-ci
    trigger: false
  - task: destroy-jumpbox
    file: azure-oss-demos-ci/jumpbox/tasks/destroy-jumpbox.yml
    params:
      service_principal_id: {{SERVICE_PRINCIPAL_ID}}
      service_principal_secret: {{SERVICE_PRINCIPAL_SECRET}}
      tenant_id: {{TENANT_ID}}
      subscription_id: {{SUBSCRIPTION_ID}}
      utility_rg: {{RG_UTILITY}}




