---
groups:
- name: Boostrap Environment
  jobs:
  - validate-input
  - create-configure-jumpbox
  - create-oms-workspace
  - create-container-registry
  - create-docker-vms
  - create-acs-kubernetes
  - create-paas-webplan
   
- name: Unprovision Environment
  jobs:
  - delete-jumpbox
  - delete-oms-workspace
  - delete-azure-container-registry
  - delete-docker-vms
  - delete-kubernetes-cluster


resources:
- name: azure-ossdemos-git
  type: git
  source:
    uri: https://github.com/schabiyo/azure-oss-demos.git
    branch: master

- name: azure-oss-demos
  type: git
  source:
    uri: https://github.com/dansand71/OSSonAzure.git
    branch: master

jobs:
- name: validate-input
  plan:
  - get: azure-ossdemos-git
    triggered: true
  - task: validate-input
    file: azure-ossdemos-git/infra-provisioning/jumpbox/tasks/validate-input.yml
    params:
      service_principal_id: {{SERVICE_PRINCIPAL_ID}}
      service_principal_secret: {{SERVICE_PRINCIPAL_SECRET}}
      tenant_id: {{TENANT_ID}}
      subscription_id: {{SUBSCRIPTION_ID}}
      storage_account_prefix: {{STORAGE_ACCOUNT_PREFIX}} 

- name: create-configure-jumpbox
  plan:
  - get: azure-ossdemos-git
    passed: [validate-input]
    triggered: true
  - get: azure-oss-demos
  - task: build-jumpbox
    file: azure-ossdemos-git/infra-provisioning/jumpbox/tasks/create-jumpbox.yml
    params:
      service_principal_id: {{SERVICE_PRINCIPAL_ID}}
      service_principal_secret: {{SERVICE_PRINCIPAL_SECRET}}
      tenant_id: {{TENANT_ID}}
      subscription_id: {{SUBSCRIPTION_ID}}
      storage_account_prefix: {{STORAGE_ACCOUNT_PREFIX}}
      jumpbox_prefix: {{SERVER_PREFIX}}
      jumpbox_admin: {{SERVER_ADMIN_USERNAME}}
      jumpbox_admin_password: {{SERVER_ADMIN_PASSWORD}}
      jumpbox_ssh_private_key: {{SERVER_SSH_PRIVATE_KEY}}
      jumpbox_ssh_public_key: {{SERVER_SSH_PUBLIC_KEY}}
      utility_rg: {{RG_UTILITY}}
      location: {{LOCATION}}
  - aggregate:
    - task: ansible-configure-dotnet-core
      file: azure-ossdemos-git/infra-provisioning/jumpbox/tasks/configure-dotnet-core.yml
    - task: ansible-configure-vs-code
      file: azure-ossdemos-git/infra-provisioning/jumpbox/tasks/configure-vs-code.yml
      params:
        jumpbox_prefix: {{SERVER_PREFIX}}
        jumpbox_admin: {{SERVER_ADMIN_USERNAME}}
        jumpbox_admin_password: {{SERVER_ADMIN_PASSWORD}}
        location: {{LOCATION}}
    - task: ansible-configure-rdp-tools
      file: azure-ossdemos-git/infra-provisioning/jumpbox/tasks/configure-rdp-tools.yml
      params:
        jumpbox_prefix: {{SERVER_PREFIX}}
        jumpbox_admin: {{SERVER_ADMIN_USERNAME}}
        jumpbox_admin_password: {{SERVER_ADMIN_PASSWORD}}
        location: {{LOCATION}} 

- name: create-oms-workspace
  serial: true
  plan:
    - get: azure-ossdemos-git
      triggered: true
      passed: [validate-input]
    - task: create-oms-workspace
      file: azure-ossdemos-git/infra-provisioning/oms/tasks/create-oms-workspace.yml
      params:
        service_principal_id: {{SERVICE_PRINCIPAL_ID}}
        service_principal_secret: {{SERVICE_PRINCIPAL_SECRET}}
        tenant_id: {{TENANT_ID}}
        subscription_id: {{SUBSCRIPTION_ID}}
        location: {{LOCATION}}
        utility_rg: {{RG_UTILITY}}
        oms_workspace_name: {{OMS_WORKSPACE_NAME}}
        oms_workspace_sku: {{OMS_WORKSPACE_SKU}}

- name: create-container-registry
  serial: true
  plan:
    - get: azure-ossdemos-git
      passed:
      - validate-input
    - task: create-container-registry
      file: azure-ossdemos-git/infra-provisioning/acr/tasks/create-acr.yml
      params:
        service_principal_id: {{SERVICE_PRINCIPAL_ID}}
        service_principal_secret: {{SERVICE_PRINCIPAL_SECRET}}
        tenant_id: {{TENANT_ID}}
        subscription_id: {{SUBSCRIPTION_ID}}
        location: {{LOCATION}}
        utility_rg: {{RG_UTILITY}}
        registry_name: {{ACR_NAME}}
        registry_sku: {{ACR_SKU}}
        registry_admin_username: {{ACR_ADMIN_USERNAME}}
        registry_admin_password: {{ACR_ADMIN_PASSWORD}}


- name: create-docker-vms
  serial: true
  plan:
    - get: azure-ossdemos-git
      passed:
      - create-oms-workspace
    - task: create-iaa-vms-init
      file: azure-ossdemos-git/infra-provisioning/iaas/tasks/create-networking-resources.yml
      params:
        service_principal_id: {{SERVICE_PRINCIPAL_ID}}
        service_principal_secret: {{SERVICE_PRINCIPAL_SECRET}}
        tenant_id: {{TENANT_ID}}
        subscription_id: {{SUBSCRIPTION_ID}}
        location: {{LOCATION}}
        utility_rg: {{RG_UTILITY}}
        oms_workspace_name: {{OMS_WORKSPACE_NAME}}
        iaas_rg: {{RG_APPDEV_IAAS}}
        server_admin_username: {{SERVER_ADMIN_USERNAME}}
        jumpbox_admin_password: {{SERVER_ADMIN_PASSWORD}}
        server_ssh_private_key: {{SERVER_SSH_PRIVATE_KEY}}
        server_ssh_public_key: {{SERVER_SSH_PUBLIC_KEY}}
        server_prefix: {{SERVER_PREFIX}}
    - aggregate:
      - task: create-iaas-vm1
        file: azure-ossdemos-git/infra-provisioning/iaas/tasks/create-iaas-vm1.yml
        params:
          service_principal_id: {{SERVICE_PRINCIPAL_ID}}
          service_principal_secret: {{SERVICE_PRINCIPAL_SECRET}}
          tenant_id: {{TENANT_ID}}
          subscription_id: {{SUBSCRIPTION_ID}}
          location: {{LOCATION}}
          utility_rg: {{RG_UTILITY}}
          oms_workspace_name: {{OMS_WORKSPACE_NAME}}
          iaas_rg: {{RG_APPDEV_IAAS}}
          server_admin_username: {{SERVER_ADMIN_USERNAME}}
          jumpbox_admin_password: {{SERVER_ADMIN_PASSWORD}}
          server_ssh_private_key: {{SERVER_SSH_PRIVATE_KEY}}
          server_ssh_public_key: {{SERVER_SSH_PUBLIC_KEY}}
          server_prefix: {{SERVER_PREFIX}}
      - task: create-iaas-vm2
        file:  azure-ossdemos-git/infra-provisioning/iaas/tasks/create-iaas-vm2.yml
        params:
          service_principal_id: {{SERVICE_PRINCIPAL_ID}}
          service_principal_secret: {{SERVICE_PRINCIPAL_SECRET}}
          tenant_id: {{TENANT_ID}}
          subscription_id: {{SUBSCRIPTION_ID}}
          location: {{LOCATION}}
          utility_rg: {{RG_UTILITY}}
          oms_workspace_name: {{OMS_WORKSPACE_NAME}}
          iaas_rg: {{RG_APPDEV_IAAS}}
          server_admin_username: {{SERVER_ADMIN_USERNAME}}
          jumpbox_admin_password: {{SERVER_ADMIN_PASSWORD}}
          server_ssh_private_key: {{SERVER_SSH_PRIVATE_KEY}}
          server_ssh_public_key: {{SERVER_SSH_PUBLIC_KEY}}
          server_prefix: {{SERVER_PREFIX}}

- name: create-acs-kubernetes
  serial: true
  plan:
    - get: azure-ossdemos-git
      passed:
      - create-oms-workspace
      - create-container-registry
    - task: create-kubernetes-cluster
      file: azure-ossdemos-git/infra-provisioning/acs/tasks/create-k8s.yml
      params:
        service_principal_id: {{SERVICE_PRINCIPAL_ID}}
        service_principal_secret: {{SERVICE_PRINCIPAL_SECRET}}
        tenant_id: {{TENANT_ID}}
        subscription_id: {{SUBSCRIPTION_ID}}
        location: {{LOCATION}}
        utility_rg: {{RG_UTILITY}}
        oms_workspace_name: {{OMS_WORKSPACE_NAME}}
        acs_rg: {{RG_ACS_K8S}}
        server_admin_username: {{SERVER_ADMIN_USERNAME}}
        server_prefix: {{SERVER_PREFIX}}
        server_ssh_private_key: {{SERVER_SSH_PRIVATE_KEY}}
        server_ssh_public_key: {{SERVER_SSH_PUBLIC_KEY}}
        registry_name: {{ACR_NAME}}
        demo_admin_email: {{ADMIN_EMAIL}}


- name: create-paas-webplan
  serial: true
  plan:
    - get: azure-ossdemos-git
      passed:
      - create-oms-workspace
    - task: create-configure-webplan
      file: azure-ossdemos-git/infra-provisioning/paas/tasks/create-webplan.yml
      params:
        service_principal_id: {{SERVICE_PRINCIPAL_ID}}
        service_principal_secret: {{SERVICE_PRINCIPAL_SECRET}}
        tenant_id: {{TENANT_ID}}
        subscription_id: {{SUBSCRIPTION_ID}}
        location: {{LOCATION}}
        utility_rg: {{RG_UTILITY}}
        oms_workspace_name: {{OMS_WORKSPACE_NAME}}
        paas_rg: {{RG_PAAS}}
        server_prefix: {{SERVER_PREFIX}}




- name: build-publish-containers
  serial: true
  plan:
    - get: azure-ossdemos-git
      passed: [create-container-registry]
    - task: build-docker-images
      file: azure-ossdemos-git/infra-provisioning/jumpbox/tasks/create-acr.yml
    - task: publish-docker-images
      file: azure-ossdemos-git/infra-provisioning/jumpbox/tasks/create-acr.yml


- name: delete-jumpbox
  serial_groups: [unprovision]
  plan:
  - get: azure-ossdemos-git
    trigger: false
    passed: [ delete-oms-workspace, delete-azure-container-registry ]
  - task: destroy-jumpbox
    file: azure-ossdemos-git/infra-provisioning/jumpbox/tasks/destroy-jumpbox.yml
    params:
      service_principal_id: {{SERVICE_PRINCIPAL_ID}}
      service_principal_secret: {{SERVICE_PRINCIPAL_SECRET}}
      tenant_id: {{TENANT_ID}}
      subscription_id: {{SUBSCRIPTION_ID}}
      utility_rg: {{RG_UTILITY}}

- name: delete-oms-workspace
  serial_groups: [unprovision]
  plan:
  - get: azure-ossdemos-git
    trigger: false
  - task: delete-oms-workspace
    file: azure-ossdemos-git/infra-provisioning/oms/tasks/delete-oms-workspace.yml
    params:
      service_principal_id: {{SERVICE_PRINCIPAL_ID}}
      service_principal_secret: {{SERVICE_PRINCIPAL_SECRET}}
      tenant_id: {{TENANT_ID}}
      subscription_id: {{SUBSCRIPTION_ID}}
      utility_rg: {{RG_UTILITY}}
      oms_workspace_name: {{OMS_WORKSPACE_NAME}}

- name: delete-azure-container-registry
  serial_groups: [unprovision]
  plan:
  - get: azure-ossdemos-git
    trigger: false
  - task: delete-azure-container-registry
    file: azure-ossdemos-git/infra-provisioning/acr/tasks/delete-acr.yml
    params:
      service_principal_id: {{SERVICE_PRINCIPAL_ID}}
      service_principal_secret: {{SERVICE_PRINCIPAL_SECRET}}
      tenant_id: {{TENANT_ID}}
      subscription_id: {{SUBSCRIPTION_ID}}
      utility_rg: {{RG_UTILITY}}

- name: delete-docker-vms
  serial_groups: [unprovision]
  plan:
  - get: azure-ossdemos-git
    trigger: false
  - task: delete-docker-vms
    file: azure-ossdemos-git/infra-provisioning/iaas/tasks/destroy-docker-vms.yml
    params:
      service_principal_id: {{SERVICE_PRINCIPAL_ID}}
      service_principal_secret: {{SERVICE_PRINCIPAL_SECRET}}
      tenant_id: {{TENANT_ID}}
      subscription_id: {{SUBSCRIPTION_ID}}
      iaas_rg: {{RG_APPDEV_IAAS}}



- name: delete-kubernetes-cluster
  serial_groups: [unprovision]
  plan:
  - get: azure-ossdemos-git
    trigger: false
  - task: delete-kubernetes-cluster
    file: azure-ossdemos-git/infra-provisioning/acs/tasks/delete-k8s.yml
    params:
      service_principal_id: {{SERVICE_PRINCIPAL_ID}}
      service_principal_secret: {{SERVICE_PRINCIPAL_SECRET}}
      tenant_id: {{TENANT_ID}}
      subscription_id: {{SUBSCRIPTION_ID}}
      acs_rg: {{RG_ACS_K8S}}
      server_prefix: {{SERVER_PREFIX}}

