---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: schabiyo/ossdemo 
    tag: latest

params:
  service_principal_id: 
  service_principal_secret:
  tenant_id:
  subscription_id:
  oms_workspace_name:
  location:
  utility_rg:
  iaas_rg:
  jumpbox_admin_password:
  server_ssh_private_key:
  server_ssh_public_key:
  server_admin_username:
  server_prefix:


inputs:
  - name: azure-ossdemos-git

outputs:
  - name: keys-out
  - name: parameters-out

run:
  path: azure-ossdemos-git/infra-provisioning/iaas/tasks/create-networking-resources.sh
