---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: ubuntu 
    tag: 14.04.5

params:
  service_principal_id: 
  service_principal_secret:
  tenant_id:
  subscription_id:


inputs:
  - name: azure-oss-demos-ci

run:
  path: azure-oss-demos-ci/jumpbox/tasks/create-oms-workspace.sh
