---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: schabiyo/ossdemo 
    tag: latest

params:
  service_principal_id: 
  service_principal_secret:
  tenant_id:
  subscription_id:


inputs:
  - name: azure-ossdemos-git

run:
  path: azure-ossdemos-git/jumpbox/tasks/create-acr.sh
