---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: schabiyo/ossdemo 
    tag: latest

params:
  service_principal_id: 
  service_principal_secret:
  tenant_id:
  subscription_id:
  utility_rg: 
  storage_account_prefix:
  jumpbox_prefix:
  jumpbox_admin:
  jumpbox_ssh_private_key:
  jumpbox_ssh_public_key:
  location: eastus


inputs:
  - name: azure-oss-demos
  - name: azure-oss-demos-ci

run:
  path: azure-oss-demos-ci/jumpbox/tasks/create-jumpbox.sh
