---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: schabiyo/ossdemo 
    tag: latest

params:
  service_principal_id: 
  service_principal_secret:
  tenant_id:
  subscription_id:
  utility_rg: 
  storage_account_prefix:
  jumpbox_prefix:
  jumpbox_admin:
  jumpbox_ssh_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEAquoMDpWEOFyP5XFJnN9A0EJ0A/81wluEZKVUHE3uf0N9t+Tn
    G+B3ozc3/ZRKlDjf32FhetFznm2HGex5WSbco1H59ZM35u2b60lNaLyxteyEpJoA
    4me6qPtEs8qQk7lsTww+xdb+472EcVc1mNxc/bZ7XwQ43hHM5pgpJ74l4TsUgZBP
    i2g1DG4MLLW3pg2wLZMV2YPh3zBEuZ2EfrvoE6I7PgV3rOiDWlp2Cga1pYE1+Jqp
    +HpAruGAMgXFWE0ixYfqEOQtU/Zp7biuX50uFvEA3fs3MkKviE1cTQ+gRT2oO0BQ
    h7KB1S62GWfeTXVDk8W7zQo5ufjFsvQ0a7k8/QIDAQABAoIBAHID1e04ss6CeP+/
    ljLO/8auPgSYkH1KXcRiQfzrxAkjtc8iJUYEdOrtoC1KaoH8euPia4vqA64RNMoH
    ZWAiu5c7zXqULfugUJ4h9UDEd+x7jnTbw3FFb1Dg5hDmNZJGZMlKyulhpgG44IxX
    eAq0HlimDiDxiRojV8QQh4vanhxkHNh5NkwzXY5OKEmYBMIwcYLsdoXjg/9jlSL5
    gHbsyEoAIta19zdMCIlYEzYd+K3DT0lhYlfh28OnoV+AL07wfhGVGuWDAp6Pr6ZE
    jnVCLWXgPBxt+OgEKuyqhavoOAsxlPO+atrUNZth8IxlGDopmPjKq684teg/spkF
    JtZkTiUCgYEA2cJ1wiPQhBpqqpMq5QLcQUyKWdkqaAxB9sgaf20n6cRloAtNVy8y
    +se7U+8/nDELWifK1fSQsofWEn+SUnAGFFCnvoWKU1vDAi02Y09YvO0qa/lRbGZE
    +dcNRBFZZFOoj4a/qgvRDOzTmfE7TjYyqqgXYFLxqsIdI0Uz8tIuGo8CgYEAyO2e
    vk1bDWCpcSRV0mhrYzTr2KCR0aP+ue2/r9aWapYWNNByPDQ23Foll3MCLXQJ8igR
    Vg3sly3GuA/omL7PPVX7Cd2EWbeiqncAr/3KDn8TeKXbGBusXsjtfnCZnkSj3oir
    32kPfBzFlpVY+UjpHhL93hAUEQVT/a2Gi2T6JbMCgYBZUUK907TWSoOP3XdNocO3
    4O4qdkHHlaeE0oTT2XDymITahWg+p3RwmnYCsnJT3WX7n7C522tyXvb2dW8N8zb7
    JC35noqjMFMnVGYni8cpDtpEmWnFXZlTJNsjHT6eQRY1cJ6y38/qTkVosiKSLPbR
    OssDzmGjmaUb72mkYoNYjwKBgFLM0TD88bu2jLzqS0+U5kQQp+wyZ0Tr/umh1u9g
    T8YGqYoEKD81CTKPF5SsuUX/3qVi65n5zPiTzaNGMwTXBNHy36u2FHdgXHFA7xCX
    Vi/ZIC4Esx/hL4wz4uLLBhMZmCn5SlKbmdz8glRGoU7BRAe3rdRX7d0BxBXy71H8
    P7VPAoGAOtG58sqhzOVtolJy/kCVscJJAOXSWDC42e01SItjB0uzgtyiFi37kXeP
    UJYSYoZevWDj1U3WQp/LFgGPXj+oktTvPyqk/68tCW/EOvDNVVpyppvpRTkINSPL
    0dbZ0OK3eNLAHfJP1VGffi+EYWlKZkOvTQE5grxZ5ZVv96URxnM=
    -----END RSA PRIVATE KEY-----
  jumpbox_ssh_public_key:
  location: eastus


inputs:
  - name: azure-oss-demos
  - name: azure-oss-demos-ci

run:
  path: azure-oss-demos-ci/jumpbox/tasks/create-jumpbox.sh
