---
platform: linux

image: docker:///java#8

params:
  MAVEN_OPTS:
  MAVEN_CONFIG:

inputs:
  - name: boot-helloworld

outputs:
  - name: package

run:
  path: azure-oss-demos/jumpbox/tasks/validate-input.sh
  args: [
    --input-dir, boot-helloworld,
    --output-dir, package,
    --artifactId, boot-helloworld,
  ]
