---
platform: linux

image: docker:///java#8

params:
  MAVEN_OPTS:
  MAVEN_CONFIG:


inputs:
  - name: azure-oss-demos

outputs:
  - name: azure-oss-demos

run:
  path: azure-oss-demos/jumpbox/tasks/validate-input.sh
