---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: schabiyo/ossdemo 
    tag: latest
#image: docker:///java#8

params:
  MAVEN_OPTS:
  MAVEN_CONFIG:


inputs:
  - name: azure-oss-demos

outputs:
  - name: ossdemo-utility

run:
  path: azure-oss-demos/jumpbox/tasks/validate-input.sh
