---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: schabiyo/ossdemo 
    tag: latest

params:
  service_principal_id: 
  service_principal_secret:
  tenant_id:
  subscription_id:
  oms_workspace_name:
  oms_workspace_sku:
  location:
  utility_rg:


inputs:
  - name: azure-ossdemos-git


run:
  path: azure-ossdemos-git/infra-provisioning/oms/tasks/create-oms-workspace.sh
