---
# This playbook installs Visual studio code
- name: Install VS Code
  hosts: buildbox
  remote_user: VALUEOF_DEMO_ADMIN_USER
  sudo : true 

  tasks: 
  - name: update YUM
    yum: name=* state=latest
  
  - name: Install epel
    yum: name=epel-release state=latest

  - name: Install python and pip
    yum: name=python-pip state=latest
  
  - name: install Git
    yum: name=git state=latest

  - name: install Ansible
    yum: name=ansible state=latest
      
# Install MS Visual Studio Code - https://code.visualstudio.com/docs/setup/linux
  - name: install vs code keys
    command: rpm --import https://packages.microsoft.com/keys/microsoft.asc
  - name: config the vs repo
    command: sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
  - name: update yum
    command: yum -y update
  - name: update the Yum cache
    command: yum check-update
  - name: install vs code for demo purposes
    yum: name=code state=latest

