---
# This playbook installs .NET Core and related tools
- name: Install .NET Core et Developer Tools 
  hosts: buildbox
  remote_user: VALUEOF_DEMO_ADMIN_USER
  sudo : true 

  tasks: 
# Install MS .NET Core - https://www.microsoft.com/net/core#linuxcentos
  - name: download the dotnet bits
    command: curl -sSL -o dotnet.tar.gz https://go.microsoft.com/fwlink/?linkid=843449
    args:
      chdir: /source
    ignore_errors: yes
  - name: install .net
    command: mkdir -p /opt/dotnet
    args:
      chdir: /source
    ignore_errors: yes
  - name: config .net
    command: tar zxf dotnet.tar.gz -C /opt/dotnet
    args:
      chdir: /source
    ignore_errors: yes
  - name: configure .net
    command: ln -s /opt/dotnet/dotnet /usr/local/bin
    ignore_errors: yes

# Install .NET Publishing Tools
  - name: install npm for .NET Publishing
    yum: name=npm state=latest
  - name: install bower
    command: npm install bower -g
  - name: install gulp
    command: npm install gulp -g

# Install developer tools
  - name: Developer Tools
    command: yum -y groupinstall "Development Tools"
