---
# This playbook installs Remote Desktop and UI tools
- name: Install Remote Desktop and UI tools
  hosts: buildbox
  remote_user: VALUEOF_DEMO_ADMIN_USER
  sudo : true 

  tasks: 
  - name: update YUM
    yum: name=* state=latest
  
  - name: Install epel
    yum: name=epel-release state=latest

  - name: Install python and pip
    yum: name=python-pip state=latest
  
  - name: install Git
    yum: name=git state=latest

  - name: install Ansible
    yum: name=ansible state=latest
      
# Install XRDP and TigerVNC - this is for RDP access and demo - http://www.itzgeek.com/how-tos/linux/centos-how-tos/install-xrdp-on-centos-7-rhel-7.html
  - name: install nux for demo purposes
    command: rpm -Uvh http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-1.el7.nux.noarch.rpm
    ignore_errors: yes
  
  - name: install XRDP for demo purposes
    yum: name=xrdp state=latest
  
  - name: install TigerVNC for demo purposes
    yum: name=tigervnc state=latest
  
  - name: Start xrdp
    service: 
      name: xrdp 
      state: running
      enabled: yes
   
# Install developer tools
  - name: Developer Tools
    command: yum -y groupinstall "Development Tools"

# Install desktop tools
  - name: Gnome
    command: yum -y groupinstall "GNOME Desktop" "Graphical Administration 
