---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: schabiyo/ossdemo 
    tag: latest

params:
  service_principal_id: 
  service_principal_secret:
  tenant_id:
  subscription_id:
  acs_rd:
  server_prefix:
  

inputs:
  - name: azure-ossdemos-git

run:
  path: azure-ossdemos-git/acs/tasks/delete-k8s.sh
